kind: Deployment
apiVersion: apps/v1
metadata:
  name: mariadb
spec:
  template:
    spec:
      volumes:
        - name: mariadb-certs
          secret:
            defaultMode: 420
            items:
              - key: tls.crt
                path: public.crt
              - key: tls.key
                path: private.key
            secretName: mariadb-certs
        - name: tls-config
          configMap:
            name: tls-config
        - name: ca-bundles
          projected:
            sources:
              - configMap:
                  name: kube-root-ca.crt
                  items:
                    - key: ca.crt
                      path: kube-root-ca.crt
              - configMap:
                  name: config-service-cabundle
                  items:
                    - key: service-ca.crt
                      path: public.crt
      containers:
        - name: mariadb
          volumeMounts:
            - mountPath: /.mariadb/certs
              name: mariadb-certs
            - mountPath: /etc/my.cnf.d/z-custom-my.cnf
              name: tls-config
              subPath: z-custom-my.cnf
            - name: ca-bundles
              mountPath: /.mariadb/certs/CAs
          terminationMessagePolicy: File